# Generated by Django 5.0.4 on 2024-04-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyOrders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=50)),
                ('ticker', models.CharField(max_length=5)),
                ('buyPrice', models.FloatField()),
                ('cashAmount', models.FloatField()),
                ('stockAmount', models.FloatField()),
                ('sellTrigger', models.FloatField()),
                ('pending', models.BooleanField()),
                ('buyDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SellOrders',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=50)),
                ('ticker', models.CharField(max_length=5)),
                ('buyPrice', models.FloatField()),
                ('cashAmount', models.FloatField()),
                ('stockAmount', models.FloatField()),
                ('sellPrice', models.FloatField()),
                ('profit', models.FloatField()),
                ('buyDate', models.DateField(default='1950-1-1')),
                ('sellDate', models.DateField(default='1950-1-1')),
            ],
        ),
    ]
