# Generated by Django 5.0.4 on 2024-04-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteMarketOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('ticker', models.CharField(max_length=5)),
                ('buyprice', models.FloatField()),
                ('cashAmount', models.FloatField()),
                ('stockAmount', models.FloatField()),
                ('sellPrice', models.FloatField()),
                ('profit', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CurrentMarketOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('ticker', models.CharField(max_length=5)),
                ('buyprice', models.FloatField()),
                ('cashAmount', models.FloatField()),
                ('stockAmount', models.FloatField()),
                ('pending', models.BooleanField()),
                ('buydate', models.DateField()),
            ],
        ),
    ]
