# Generated by Django 5.0.4 on 2024-04-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellorders',
            name='buydate',
            field=models.DateField(default='1950-1-1'),
        ),
        migrations.AddField(
            model_name='sellorders',
            name='sellDate',
            field=models.DateField(default='1950-1-1'),
        ),
    ]
