# Generated by Django 5.0.4 on 2024-05-01 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyorders',
            name='pending',
        ),
    ]
