# Generated by Django 5.0.4 on 2024-04-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersApp', '0002_sellorders_buydate_sellorders_selldate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellorders',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
