# Generated by Django 5.0.4 on 2024-05-01 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersApp', '0002_remove_buyorders_pending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyorders',
            name='sellTrigger',
        ),
    ]
