# Generated by Django 5.0.4 on 2024-04-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersApp', '0003_alter_sellorders_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyorders',
            old_name='buydate',
            new_name='buyDate',
        ),
        migrations.RenameField(
            model_name='buyorders',
            old_name='buyprice',
            new_name='buyPrice',
        ),
        migrations.RenameField(
            model_name='sellorders',
            old_name='buydate',
            new_name='buyDate',
        ),
        migrations.RenameField(
            model_name='sellorders',
            old_name='buyprice',
            new_name='buyPrice',
        ),
        migrations.AlterField(
            model_name='sellorders',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
