# Generated by Django 5.0.4 on 2024-04-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPortfolio',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('portfolioAmount', models.FloatField()),
            ],
        ),
    ]
