# Generated by Django 5.0.4 on 2024-05-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userportfolio',
            old_name='portfolioAmount',
            new_name='totalPortfolioAmount',
        ),
        migrations.AddField(
            model_name='userportfolio',
            name='investedAmount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userportfolio',
            name='liquidAmount',
            field=models.FloatField(default=0.0),
        ),
    ]
