# Generated by Django 5.0.4 on 2024-05-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0002_rename_portfolioamount_userportfolio_totalportfolioamount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userportfolio',
            name='liquidAmount',
            field=models.FloatField(default=25000),
        ),
    ]
